variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "private_subnet1_cidr" {}
variable "private_subnet2_cidr" {}
variable "repository_name" {}
variable "cluster_name" {}
variable "container_port" {}
variable "host_port" {}
variable "service_name" {}
variable "sports_api_key" {}